"""
Utilities for processing telemetry data from the Second Monitor application.
Includes functions for parsing session times, interpolating telemetry fields,
and exporting data to RaceBox CSV format.
"""
import os
import json
import csv
import numpy as np

from datetime import datetime, timedelta


from race_tools import rfactor

# When testing that the software and sim rig are working I don't want to skew main driver stats.
KART_DRIVER_MAPPING = {
    '8': 'Alexey',
}


def parse_session_time(time_str: str) -> float:
    """
    Parse HH:MM:SS.ffffff string into total seconds.

    Args:
        time_str: Time string in format HH:MM:SS.ffffff.

    Returns:
        Total seconds as a float.
    """
    parts = time_str.split(':')
    if len(parts) == 3:
        h, m, s = parts
        return int(h) * 3600 + int(m) * 60 + float(s)
    return 0.0


def interpolate_fields(points: list[dict], field_paths: list[list[str]]) -> None:
    """
    Interpolates specified fields for points where TimeInterpolated is true.

    Uses a 4-point local spline (interpolating polynomial of degree 3) to fill in
    missing data points generated by the simulator.

    Args:
        points: List of telemetry data point dictionaries.
        field_paths: List of paths (as list of keys) to the fields that should be interpolated.

    Note:
        Points must be sorted by time and belong to the same lap to avoid distance wraps.
    """
    if len(points) < 4:
        return

    times = np.array([parse_session_time(p.get('SessionTime', '0')) for p in points])
    is_interpolated = np.array([p.get('SimulatorSourceInfo', {}).get('TimeInterpolated', False) for p in points])

    anchor_indices = np.where(~is_interpolated)[0]
    if len(anchor_indices) < 4:
        return

    num_anchors = len(anchor_indices)

    def get_nested_val(data: dict, path: list[str]) -> float:
        curr = data
        for k in path:
            if not isinstance(curr, dict):
                return 0.0
            curr = curr.get(k, 0.0)
        return float(curr) if isinstance(curr, (int, float)) else 0.0

    def set_nested_val(data: dict, path: list[str], value: float) -> None:
        curr = data
        for k in path[:-1]:
            curr = curr.setdefault(k, {})
        curr[path[-1]] = value
    for path in field_paths:
        values = np.array([get_nested_val(p, path) for p in points])

        for i in range(len(points)):
            if not is_interpolated[i]:
                continue

            # Find segment of anchors
            j = np.searchsorted(anchor_indices, i) - 1
            idx_start = max(0, min(j - 1, num_anchors - 4))
            local_anchors = anchor_indices[idx_start:idx_start + 4]

            x_local = times[local_anchors]
            y_local = values[local_anchors]

            # Fit polynomial of degree 3 to 4 points
            poly = np.polyfit(x_local, y_local, 3)
            new_val = np.polyval(poly, times[i])

            # Set value back
            set_nested_val(points[i], path, float(new_val))


def extract_driver_telemetry(session_path: str, driver_name: str, kart_number: str = '') -> list[dict]:
    """
    Extracts all telemetry points for a specific driver from a Second Monitor session folder.

    Args:
        session_path: Path to the folder containing Second Monitor session JSON files.
        driver_name: The name of the driver to extract data for.
        kart_number: Optional kart number to assist with driver identification mapping.

    Returns:
        A list of telemetry data point dictionaries, sorted by session time.
    """
    all_points = []
    json_files = [f for f in os.listdir(session_path) if f.endswith('.json')]

    for j_file in json_files:
        j_path = os.path.join(session_path, j_file)
        with open(j_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
            d_name = data.get('LapSummary', {}).get('DriverName', '')

            # Apply mapping
            if kart_number in KART_DRIVER_MAPPING:
                d_name = KART_DRIVER_MAPPING[kart_number]

            if d_name != driver_name:
                continue

            lap_num = data.get('LapSummary', {}).get('LapNumber', 0)
            d_points = data.get('DataPoints', [])
            for pt in d_points:
                pt['_lap_num'] = lap_num
                all_points.append(pt)

    if not all_points:
        return []

    # Sort by SessionTime
    all_points.sort(key=lambda x: parse_session_time(x.get('SessionTime', '0')))

    # Process interpolation lap-by-lap to avoid spline spikes at lap boundaries
    lap_nums = sorted(list(set(pt.get('_lap_num', 0) for pt in all_points)))
    for l_num in lap_nums:
        lap_pts = [pt for pt in all_points if pt.get('_lap_num', 0) == l_num]
        interpolate_fields(lap_pts, [
            ['PlayerData', 'LapDistance'],
            ['PlayerData', 'WorldPosition', 'X', 'InMeters'],
            ['PlayerData', 'WorldPosition', 'Y', 'InMeters'],
            ['PlayerData', 'WorldPosition', 'Z', 'InMeters'],
            ['PlayerData', 'Speed', 'InMs']
        ])

    return all_points


def write_telemetry_to_csv(
    output_path: str,
    points: list[dict],
    track_name_raw: str,
    driver_name: str,
    session_dt: datetime | None = None
) -> None:
    """
    Writes telemetry points to a RaceBox formatted CSV file.

    Args:
        output_path: Path where the CSV file should be saved.
        points: List of telemetry data point dictionaries.
        track_name_raw: Raw name of the track.
        driver_name: Name of the driver.
        session_dt: Optional datetime of the session start.
    """
    if not points:
        return

    origin = rfactor.get_track_origin(track_name_raw.replace('_', ' '))

    rows = []
    last_processed_time = None
    record_count = 0
    unique_laps = set()

    for pt in points:
        abs_time_sec = parse_session_time(pt.get('SessionTime', ''))

        # Deduplication
        if last_processed_time is not None and abs_time_sec <= last_processed_time:
            continue
        last_processed_time = abs_time_sec

        record_count += 1
        l_num = pt.get('_lap_num', 0)
        if l_num > 0:
            unique_laps.add(l_num)

        if session_dt:
            point_dt = session_dt + timedelta(seconds=abs_time_sec)
            # Ensure it's UTC format for RaceBox compatibility if needed
            timestamp_str = point_dt.strftime('%Y-%m-%dT%H:%M:%S.%f')[:-3] + 'Z'
        else:
            timestamp_str = f'{abs_time_sec:.3f}'

        pos = pt.get('PlayerData', {}).get('WorldPosition', {})
        x = pos.get('X', {}).get('InMeters', 0)
        y = max(0.0, pos.get('Y', {}).get('InMeters', 0))
        z = pos.get('Z', {}).get('InMeters', 0)

        lat, lon = rfactor.rfactor_to_gps(-x, z, origin)
        speed_ms = pt.get('PlayerData', {}).get('Speed', {}).get('InMs', 0)

        accel = pt.get('PlayerData', {}).get('CarInfo', {}).get('Acceleration', {})
        g_lat = -accel.get('XinMs', 0) / 9.80665
        g_lon = accel.get('ZinMs', 0) / 9.80665
        g_vert = accel.get('YinMs', 0) / 9.80665

        # Extract inputs
        input_info = pt.get('InputInfo', {})
        throttle = input_info.get('ThrottlePedalPosition', 0) * 100.0
        brake = input_info.get('BrakePedalPosition', 0) * 100.0

        # Extract Wheel Data
        wheels = pt.get('PlayerData', {}).get('CarInfo', {}).get('WheelsInfo', {})
        # Note: The 'Slip' field in the JSON is unfortunately 0.0 for this sim,
        # so we export RPS (rotation speed) which is used to calculate slip.
        rps_fl = wheels.get('FrontLeft', {}).get('Rps', 0.0)
        rps_fr = wheels.get('FrontRight', {}).get('Rps', 0.0)
        rps_rl = wheels.get('RearLeft', {}).get('Rps', 0.0)
        rps_rr = wheels.get('RearRight', {}).get('Rps', 0.0)

        # Extract WheelAngle (Already in degrees in JSON)
        wheel_angle_deg = input_info.get('WheelAngle', 0.0)

        lap_dist = pt.get('PlayerData', {}).get('LapDistance', 0.0)

        row = [
            record_count,
            timestamp_str,
            f'{lat:.8f}', f'{lon:.8f}', f'{y:.2f}',
            f'{speed_ms:.5f}',
            f'{g_lat:.3f}', f'{g_lon:.3f}', f'{g_vert:.3f}',
            f'{throttle:.1f}', f'{brake:.1f}',
            f'{wheel_angle_deg:.1f}',
            f'{rps_fl:.2f}', f'{rps_fr:.2f}', f'{rps_rl:.2f}', f'{rps_rr:.2f}',
            f'{lap_dist:.2f}',
            l_num
        ]
        rows.append(row)

    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    with open(output_path, 'w', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(['Format', 'RaceBox CSV'])
        writer.writerow(['Data Source', 'KartSim'])
        writer.writerow(['Date UTC', session_dt.strftime('%Y-%m-%dT%H:%M:%SZ') if session_dt else ''])
        writer.writerow(['Date', session_dt.strftime('%d/%m/%Y') if session_dt else ''])
        writer.writerow(['Time', session_dt.strftime('%H:%M:%S') if session_dt else ''])
        writer.writerow(['Session Index', '1'])
        writer.writerow(['Session Type', 'Track'])
        writer.writerow(['Track', track_name_raw])
        writer.writerow(['Configuration', driver_name])
        writer.writerow(['Laps', str(len(unique_laps))])
        writer.writerow([])  # Mandatory empty row

        headers = [
            'Record', 'Time', 'Latitude', 'Longitude', 'Altitude (m)',
            'Speed (m/s)', 'GForceX (g)', 'GForceY (g)', 'GForceZ (g)',
            'Throttle (%)', 'Brake (%)', 'Steering Wheel Angle (deg)',
            'RPS FL', 'RPS FR', 'RPS RL', 'RPS RR',
            'Lap Distance (m)', 'Lap'
        ]
        writer.writerow(headers)
        writer.writerows(rows)
